// Sage Clinical Workspace: compact doctor profile. Full availability remains on the existing doctor-specific Schedule page.
import { useEffect, useState } from 'react';
import { Link, useLocation, useNavigate, useOutletContext, useParams } from 'react-router-dom';
import { CalendarDays, MapPin, Phone, Stethoscope } from 'lucide-react';
import apiClient from '../../services/apiClient.js';
import ConfirmDialog from '../../components/ConfirmDialog.jsx';
import PageHeader from '../../components/PageHeader.jsx';
import { ErrorPanel, LoadingPanel } from '../../components/StatePanel.jsx';
import { StatusBadge } from '../patients/PatientsIndex.jsx';
import { usePermissions } from '../../hooks/usePermissions.js';

export default function DoctorShow() {
  const { doctorId } = useParams(); const location = useLocation(); const navigate = useNavigate(); const { user } = useOutletContext(); const { can } = usePermissions(user); const [doctor, setDoctor] = useState(null); const [error, setError] = useState(''); const [confirm, setConfirm] = useState(false); const [deleting, setDeleting] = useState(false); const [notice] = useState(location.state?.notice || '');
  const load = () => { setDoctor(null); apiClient.get(`/doctors/${doctorId}`).then((response) => setDoctor(response.data.data)).catch((requestError) => setError(requestError?.message || 'Unable to load this doctor record.')); };
  useEffect(load, [doctorId]);
  const remove = async () => { setDeleting(true); try { await apiClient.delete(`/doctors/${doctorId}`); navigate('/doctors', { state: { notice: 'Doctor record deleted.' } }); } catch (requestError) { setError(requestError?.message || 'Unable to delete this doctor record.'); setConfirm(false); } finally { setDeleting(false); } };
  if (error) return <section className="routed-page"><ErrorPanel message={error} retry={load} /></section>;
  if (!doctor) return <section className="routed-page"><LoadingPanel label="Loading doctor profile…" /></section>;
  return <section className="routed-page profile-page doctor-profile-page"><PageHeader eyebrow="CLINICAL TEAM · DOCTOR PROFILE" title="Doctor profile" description="Professional record and contact details." crumbs={[{ label: 'Doctors', to: '/doctors' }, { label: doctor.name }]} action={<div className="profile-actions"><Link className="btn-ledger-secondary" to="/doctors">← Back to doctors</Link>{can('doctors.update') && <Link className="btn-ledger-primary" to={`/doctors/${doctor.id}/edit`}>Edit profile</Link>}</div>} />{notice && <div className="form-notice">{notice}</div>}<section className="doctor-profile-cover"><div className="doctor-profile-cover-pattern" aria-hidden="true" /><div className="doctor-profile-identity"><DoctorAvatar doctor={doctor} /><div><span>{doctor.registration_number || 'DOCTOR RECORD'}</span><h2>{doctor.name}</h2><p><Stethoscope />{doctor.specialization || 'Specialty not recorded'}<b>·</b>{doctor.department?.name || 'Department not recorded'}</p></div><StatusBadge value={doctor.status} /></div><div className="doctor-profile-actions"><Link className="btn-ledger-primary" to={`/doctors/${doctor.id}/schedules`}><CalendarDays />View Schedule →</Link></div></section><div className="doctor-profile-grid"><ProfileCard title="Professional summary" icon={<Stethoscope />} data={[['Specialty', doctor.specialization], ['Department', doctor.department?.name], ['Qualification', doctor.qualification], ['Experience', doctor.experience_years != null ? `${doctor.experience_years} years` : null], ['Registration', doctor.registration_number], ['Consultation fee', doctor.consultation_fee != null ? `৳${Number(doctor.consultation_fee).toFixed(2)}` : null]]} /><ProfileCard title="Contact information" icon={<Phone />} data={[['Phone', doctor.phone], ['Email', doctor.email], ['Address', doctor.address]]} /><ProfileCard title="Personal record" icon={<MapPin />} data={[['Gender', doctor.gender], ['Date of birth', doctor.date_of_birth]]} /></div>{can('doctors.delete') && <button className="profile-delete-link" type="button" onClick={() => setConfirm(true)}>Delete this doctor record</button>}{confirm && <ConfirmDialog title="Delete doctor record" description={`Delete ${doctor.name}? The doctor record will be soft-deleted.`} busy={deleting} onCancel={() => setConfirm(false)} onConfirm={remove} />}</section>;
}
function DoctorAvatar({ doctor }) { const initials = String(doctor.name || 'Doctor').replace(/^Dr\.\s*/i, '').split(/\s+/).slice(0, 2).map((item) => item[0]).join('').toUpperCase(); return <div className="doctor-profile-avatar" aria-label={`${doctor.name} initials`}><Stethoscope /><b>{initials}</b></div>; }
function ProfileCard({ title, icon, data }) { const available = data.filter(([, value]) => value); return <article className="doctor-profile-card"><header>{icon}<span>{title}</span></header>{available.length ? available.map(([label, value]) => <div key={label}><b>{label}</b><p>{value}</p></div>) : <p className="profile-empty">No additional information recorded.</p>}</article>; }
