// Reference clinical workspace: a clear bed ledger that foregrounds availability, ward context, and safe status control.
import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import apiClient from '../../services/apiClient.js';
import PageHeader from '../../components/PageHeader.jsx';
import { ErrorPanel, LoadingPanel } from '../../components/StatePanel.jsx';
import Pagination from '../../components/Pagination.jsx';
import { FormSection, SelectField, TextField } from '../phase3/ClinicalFields.jsx';
import { notify } from '../../services/notify.js';

const bedTypes = [['general', 'General'], ['private', 'Private'], ['icu', 'ICU'], ['isolation', 'Isolation'], ['pediatric', 'Pediatric'], ['maternity', 'Maternity']];
const statuses = [['available', 'Available'], ['occupied', 'Occupied'], ['reserved', 'Reserved'], ['maintenance', 'Maintenance']];
const unpack = (response) => response.data.data?.items || response.data.data || [];

export function BedsIndex() {
  const [beds, setBeds] = useState([]); const [pagination, setPagination] = useState({}); const [page, setPage] = useState(1); const [filters, setFilters] = useState({ status: '', search: '' }); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = (requestedPage = page) => { setLoading(true); const params = new URLSearchParams({ page: String(requestedPage), per_page: '10' }); if (filters.status) params.set('status', filters.status); if (filters.search) params.set('search', filters.search); apiClient.get(`/beds?${params}`).then((res) => { const data = res.data.data || {}; setBeds(data.items || []); setPagination(data.pagination || {}); setPage(requestedPage); setError(''); }).catch((err) => setError(err?.response?.data?.message || 'Unable to load beds.')).finally(() => setLoading(false)); };
  useEffect(() => { load(1); }, [filters.status]);
  const remove = async (bed) => { const confirmation = await notify.confirm({ title: `Delete bed ${bed.bed_number}?`, text: 'A bed assigned to an active admission cannot be deleted.', confirmButtonText: 'Delete bed' }); if (!confirmation.isConfirmed) return; try { await apiClient.delete(`/beds/${bed.id}`); load(); } catch (err) { setError(err?.message || 'Unable to delete bed.'); notify.error(err, 'Unable to delete bed.'); } };
  if (loading) return <section className="routed-page"><LoadingPanel label="Loading bed availability…" /></section>; if (error && !beds.length) return <section className="routed-page"><ErrorPanel message={error} retry={load} /></section>;
  return <section className="routed-page phase4-page"><PageHeader eyebrow="PHASE 4 · INPATIENT" title="Bed availability" description="Review room-level capacity and configure beds without overriding admission workflow states." crumbs={[{ label: 'Beds' }]} action={<Link className="btn-ledger-primary" to="/beds/new">Add bed</Link>} /><section className="reference-surface phase4-filter-bar"><input className="form-control" value={filters.search} onChange={(event) => setFilters((current) => ({ ...current, search: event.target.value }))} onKeyDown={(event) => { if (event.key === 'Enter') { setPage(1); load(1); } }} placeholder="Search bed or room" /><select className="form-select" value={filters.status} onChange={(event) => setFilters((current) => ({ ...current, status: event.target.value }))}><option value="">All statuses</option>{statuses.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><button type="button" className="btn-ledger-secondary" onClick={() => { setPage(1); load(1); }}>Apply</button><span className="phase4-availability">{pagination.total ?? beds.length} records · {beds.filter((bed) => bed.status === 'available').length} on this page available</span></section>{error && <p className="phase4-inline-error">{error}</p>}<section className="reference-surface phase4-table-surface"><div className="table-responsive"><table className="table clinical-table"><thead><tr><th>Bed</th><th>Ward / room</th><th>Type</th><th>Availability</th><th /></tr></thead><tbody>{beds.map((bed) => <tr key={bed.id}><td><strong>{bed.name || bed.bed_number}</strong><small>{bed.name ? bed.bed_number : 'Bed identifier'}</small></td><td>{bed.room?.ward?.name || 'Unassigned ward'}<small>{bed.room?.room_number || `Room #${bed.room_id}`}</small></td><td>{bed.bed_type}</td><td><span className={`status-pill status-${bed.status}`}>{bed.status}</span></td><td className="row-actions"><Link to={`/beds/${bed.id}`}>View</Link><Link to={`/beds/${bed.id}/edit`}>Edit</Link><button type="button" disabled={bed.status === 'occupied'} onClick={() => remove(bed)}>Delete</button></td></tr>)}</tbody></table></div>{!beds.length && <div className="phase4-empty">No beds match these controls.</div>}<Pagination meta={pagination} page={page} onChange={(nextPage) => load(nextPage)} /></section></section>;
}

function BedForm({ bed, onSaved, onCancel }) {
  const [catalogue, setCatalogue] = useState({ clinics: [], rooms: [] }); const [record, setRecord] = useState(bed || { clinic_id: '', room_id: '', bed_number: '', name: '', bed_type: 'general', status: 'available', description: '' }); const [errors, setErrors] = useState({}); const [saving, setSaving] = useState(false);
  useEffect(() => { Promise.all([apiClient.get('/clinics?per_page=100'), apiClient.get('/rooms?per_page=100')]).then(([clinics, rooms]) => setCatalogue({ clinics: unpack(clinics), rooms: unpack(rooms) })).catch(() => setErrors({ form: ['Unable to load room catalogue.'] })); }, []);
  const rooms = catalogue.rooms.filter((room) => !record.clinic_id || String(room.clinic_id) === String(record.clinic_id)); const change = (field) => (value) => setRecord((current) => ({ ...current, [field]: value, ...(field === 'clinic_id' ? { room_id: '' } : {}) }));
  const submit = async (event) => { event.preventDefault(); setSaving(true); setErrors({}); const data = { ...record, clinic_id: Number(record.clinic_id), room_id: Number(record.room_id), name: record.name || null, description: record.description || null }; try { const res = bed ? await apiClient.put(`/beds/${bed.id}`, data) : await apiClient.post('/beds', data); onSaved(res.data.data); } catch (err) { setErrors(err?.response?.data?.errors || { form: [err?.response?.data?.message || 'Unable to save bed.'] }); } finally { setSaving(false); } };
  return <form className="clinical-form" onSubmit={submit}>{errors.form?.map((message) => <p className="phase4-inline-error" key={message}>{message}</p>)}<FormSection title="Bed allocation" caption="A bed must belong to a room within the selected clinic."><SelectField label="Clinic" required value={record.clinic_id} options={catalogue.clinics.map((clinic) => [clinic.id, clinic.name])} onChange={change('clinic_id')} error={errors.clinic_id} /><SelectField label="Room" required disabled={!record.clinic_id} value={record.room_id} options={rooms.map((room) => [room.id, `${room.ward?.name ? `${room.ward.name} · ` : ''}${room.room_number}${room.name ? ` — ${room.name}` : ''}`])} onChange={change('room_id')} error={errors.room_id} /><TextField label="Bed number" required value={record.bed_number} onChange={change('bed_number')} error={errors.bed_number} placeholder="e.g. A-01" /><TextField label="Display name" value={record.name} onChange={change('name')} error={errors.name} placeholder="Optional clinical label" /><SelectField label="Bed type" required value={record.bed_type} options={bedTypes} onChange={change('bed_type')} error={errors.bed_type} /><SelectField label="Status" required disabled={bed?.status === 'occupied'} value={record.status} options={statuses} onChange={change('status')} error={errors.status} /></FormSection><FormSection title="Operational note" caption="Optional non-clinical context for bed planning."><TextField label="Description" area value={record.description} onChange={change('description')} error={errors.description} /></FormSection><div className="form-actions"><button type="button" className="btn-ledger-secondary" onClick={onCancel}>Cancel</button><button className="btn-ledger-primary" disabled={saving}>{saving ? 'Saving…' : bed ? 'Save bed' : 'Create bed'}</button></div></form>;
}
export function BedCreate() { const navigate = useNavigate(); return <section className="routed-page phase4-page"><PageHeader eyebrow="PHASE 4 · INPATIENT" title="Add bed" description="Create a room-level inpatient bed with a safe initial availability state." crumbs={[{ label: 'Beds', to: '/beds' }, { label: 'Add bed' }]} /><BedForm onSaved={(bed) => navigate(`/beds/${bed.id}`)} onCancel={() => navigate('/beds')} /></section>; }
export function BedEdit() { const { bedId } = useParams(); const navigate = useNavigate(); const [bed, setBed] = useState(null); const [error, setError] = useState(''); useEffect(() => { apiClient.get(`/beds/${bedId}`).then((res) => setBed(res.data.data)).catch((err) => setError(err?.response?.data?.message || 'Unable to load bed.')); }, [bedId]); if (error) return <section className="routed-page"><ErrorPanel message={error} retry={() => window.location.reload()} /></section>; if (!bed) return <section className="routed-page"><LoadingPanel label="Loading bed…" /></section>; return <section className="routed-page phase4-page"><PageHeader eyebrow="PHASE 4 · INPATIENT" title={`Edit ${bed.bed_number}`} description="Bed status remains protected by the admission, transfer, and discharge workflows." crumbs={[{ label: 'Beds', to: '/beds' }, { label: bed.bed_number, to: `/beds/${bed.id}` }, { label: 'Edit' }]} /><BedForm bed={bed} onSaved={(saved) => navigate(`/beds/${saved.id}`)} onCancel={() => navigate(`/beds/${bed.id}`)} /></section>; }
export function BedShow() { const { bedId } = useParams(); const [bed, setBed] = useState(null); const [error, setError] = useState(''); useEffect(() => { apiClient.get(`/beds/${bedId}`).then((res) => setBed(res.data.data)).catch((err) => setError(err?.response?.data?.message || 'Unable to load bed.')); }, [bedId]); if (error) return <section className="routed-page"><ErrorPanel message={error} retry={() => window.location.reload()} /></section>; if (!bed) return <section className="routed-page"><LoadingPanel label="Loading bed details…" /></section>; return <section className="routed-page phase4-page facility-detail-page"><PageHeader eyebrow="PHASE 4 · INPATIENT" title={bed.name || bed.bed_number} description="Bed allocation, room context, and current protected availability state." crumbs={[{ label: 'Beds', to: '/beds' }, { label: bed.bed_number }]} action={<div className="profile-actions"><Link className="btn-ledger-secondary" to="/beds">Back to beds</Link><Link className="btn-ledger-primary" to={`/beds/${bed.id}/edit`}>Edit bed</Link></div>} /><section className="reference-surface facility-detail-cards"><article><span>BED NUMBER</span><strong>{bed.bed_number}</strong></article><article><span>DISPLAY NAME</span><strong>{bed.name || 'Not set'}</strong></article><article><span>WARD / ROOM</span><strong>{bed.room?.ward?.name || 'Unassigned ward'} · {bed.room?.room_number || `Room #${bed.room_id}`}</strong></article><article><span>BED TYPE</span><strong>{bed.bed_type}</strong></article><article><span>STATUS</span><strong><span className={`status-pill status-${bed.status}`}>{bed.status}</span></strong></article><article className="is-wide"><span>DESCRIPTION</span><strong>{bed.description || 'No operational note recorded.'}</strong></article></section></section>; }
