// Reference clinical workspace: light, structured ward operations with compact teal action cues and explicit clinic context.
import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import apiClient from '../../services/apiClient.js';
import PageHeader from '../../components/PageHeader.jsx';
import { ErrorPanel, LoadingPanel } from '../../components/StatePanel.jsx';
import Pagination from '../../components/Pagination.jsx';
import { FormSection, SelectField, TextField } from '../phase3/ClinicalFields.jsx';
import { notify } from '../../services/notify.js';

const wardTypes = [['general', 'General ward'], ['male', 'Male ward'], ['female', 'Female ward'], ['pediatric', 'Pediatric ward'], ['maternity', 'Maternity ward'], ['icu', 'ICU'], ['isolation', 'Isolation'], ['private', 'Private ward']];
const statuses = [['active', 'Active'], ['inactive', 'Inactive'], ['maintenance', 'Maintenance']];
const payload = (record) => ({ clinic_id: Number(record.clinic_id), name: record.name, ward_type: record.ward_type, description: record.description || null, status: record.status });

export function WardsIndex() {
  const [wards, setWards] = useState([]); const [meta, setMeta] = useState({}); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  // Backend returns { items, pagination } (see WardController::pagination()) — not a bare array.
  const load = (requested = page) => { setLoading(true); apiClient.get('/wards', { params: { page: requested } }).then((res) => { const data = res.data.data || {}; setWards(data.items || []); setMeta(data.pagination || {}); setError(''); }).catch((err) => setError(err?.response?.data?.message || err?.message || 'Unable to load wards.')).finally(() => setLoading(false)); };
  useEffect(() => load(1), []);
  const remove = async (ward) => { const confirmation = await notify.confirm({ title: `Delete ${ward.name}?`, text: 'A ward with dependent rooms or inpatient records may not be deleted.', confirmButtonText: 'Delete ward' }); if (!confirmation.isConfirmed) return; try { await apiClient.delete(`/wards/${ward.id}`); load(page); } catch (err) { setError(err?.message || 'Unable to delete this ward.'); notify.error(err, 'Unable to delete this ward.'); } };
  if (loading) return <section className="routed-page"><LoadingPanel label="Loading ward register…" /></section>;
  if (error && !wards.length) return <section className="routed-page"><ErrorPanel message={error} retry={() => load(page)} /></section>;
  return <section className="routed-page phase4-page"><PageHeader eyebrow="INPATIENT" title="Ward register" description="Define active inpatient wards before assigning rooms and beds." crumbs={[{ label: 'Wards' }]} action={<Link className="btn-ledger-primary" to="/wards/new">Add ward</Link>} />{error && <p className="phase4-inline-error">{error}</p>}<section className="reference-surface phase4-table-surface"><div className="phase4-surface-title"><span>WARD DIRECTORY</span><strong>{meta.total ?? wards.length} configured</strong></div>{wards.length ? <><div className="table-responsive"><table className="table clinical-table"><thead><tr><th>Ward</th><th>Clinic</th><th>Type</th><th>Rooms</th><th>Status</th><th /></tr></thead><tbody>{wards.map((ward) => <tr key={ward.id}><td><strong>{ward.name}</strong><small>{ward.description || 'No ward note recorded.'}</small></td><td>{ward.clinic?.name || `Clinic #${ward.clinic_id}`}</td><td><span className="status-pill">{ward.ward_type}</span></td><td>{ward.rooms_count ?? 0}</td><td><span className={`status-pill status-${ward.status}`}>{ward.status}</span></td><td className="row-actions"><Link to={`/wards/${ward.id}`}>View</Link><Link to={`/wards/${ward.id}/edit`}>Edit</Link><button type="button" onClick={() => remove(ward)}>Delete</button></td></tr>)}</tbody></table></div><Pagination meta={meta} page={page} onChange={(next) => { setPage(next); load(next); }} /></> : <div className="phase4-empty">No wards have been configured. Create the first ward to begin IPD bed planning.</div>}</section></section>;
}

function WardForm({ ward, onSaved, onCancel }) {
  const [clinics, setClinics] = useState([]); const [record, setRecord] = useState(ward || { clinic_id: '', name: '', ward_type: 'general', description: '', status: 'active' }); const [errors, setErrors] = useState({}); const [saving, setSaving] = useState(false);
  useEffect(() => { apiClient.get('/clinics?per_page=100').then((res) => setClinics(res.data.data?.items || res.data.data || [])).catch(() => setErrors({ clinic_id: ['Unable to load clinics.'] })); }, []);
  const change = (field) => (value) => setRecord((current) => ({ ...current, [field]: value }));
  const submit = async (event) => { event.preventDefault(); setSaving(true); setErrors({}); try { const res = ward ? await apiClient.put(`/wards/${ward.id}`, payload(record)) : await apiClient.post('/wards', payload(record)); onSaved(res.data.data); } catch (err) { setErrors(err?.response?.data?.errors || { form: [err?.response?.data?.message || 'Unable to save ward.'] }); } finally { setSaving(false); } };
  return <form className="clinical-form" onSubmit={submit}>{errors.form?.map((message) => <p className="phase4-inline-error" key={message}>{message}</p>)}<FormSection title="Ward identity" caption="Link the ward to its owning clinic and choose the operating classification."><SelectField label="Clinic" required value={record.clinic_id} options={clinics.map((clinic) => [clinic.id, clinic.name])} onChange={change('clinic_id')} error={errors.clinic_id} /><TextField label="Ward name" required value={record.name} onChange={change('name')} error={errors.name} placeholder="e.g. North general ward" /><SelectField label="Ward type" required value={record.ward_type} options={wardTypes} onChange={change('ward_type')} error={errors.ward_type} /><SelectField label="Status" required value={record.status} options={statuses} onChange={change('status')} error={errors.status} /></FormSection><FormSection title="Operational note" caption="Optional context for the clinical operations team."><TextField label="Description" area value={record.description} onChange={change('description')} error={errors.description} placeholder="Scope, staffing, or care notes" /></FormSection><div className="form-actions"><button type="button" className="btn-ledger-secondary" onClick={onCancel}>Cancel</button><button className="btn-ledger-primary" disabled={saving}>{saving ? 'Saving…' : ward ? 'Save ward' : 'Create ward'}</button></div></form>;
}

export function WardCreate() { const navigate = useNavigate(); return <section className="routed-page phase4-page"><PageHeader eyebrow="INPATIENT" title="Create ward" description="Establish a clinic-scoped ward before room and bed assignment." crumbs={[{ label: 'Wards', to: '/wards' }, { label: 'Create ward' }]} /><WardForm onSaved={(ward) => navigate(`/wards/${ward.id}`)} onCancel={() => navigate('/wards')} /></section>; }
export function WardEdit() { const { wardId } = useParams(); const navigate = useNavigate(); const [ward, setWard] = useState(null); const [error, setError] = useState(''); useEffect(() => { apiClient.get(`/wards/${wardId}`).then((res) => setWard(res.data.data)).catch((err) => setError(err?.response?.data?.message || 'Unable to load ward.')); }, [wardId]); if (error) return <section className="routed-page"><ErrorPanel message={error} retry={() => window.location.reload()} /></section>; if (!ward) return <section className="routed-page"><LoadingPanel label="Loading ward…" /></section>; return <section className="routed-page phase4-page"><PageHeader eyebrow="INPATIENT" title={`Edit ${ward.name}`} description="Maintain the ward's clinic relationship and operational status." crumbs={[{ label: 'Wards', to: '/wards' }, { label: ward.name, to: `/wards/${ward.id}` }, { label: 'Edit' }]} /><WardForm ward={ward} onSaved={(saved) => navigate(`/wards/${saved.id}`)} onCancel={() => navigate(`/wards/${ward.id}`)} /></section>; }
export function WardShow() { const { wardId } = useParams(); const [ward, setWard] = useState(null); const [error, setError] = useState(''); useEffect(() => { apiClient.get(`/wards/${wardId}`).then((res) => setWard(res.data.data)).catch((err) => setError(err?.response?.data?.message || 'Unable to load ward.')); }, [wardId]); if (error) return <section className="routed-page"><ErrorPanel message={error} retry={() => window.location.reload()} /></section>; if (!ward) return <section className="routed-page"><LoadingPanel label="Loading ward details…" /></section>; return <section className="routed-page phase4-page facility-detail-page"><PageHeader eyebrow="INPATIENT" title={ward.name} description="Ward details, clinic context, capacity, and current operating status." crumbs={[{ label: 'Wards', to: '/wards' }, { label: ward.name }]} action={<div className="profile-actions"><Link className="btn-ledger-secondary" to="/wards">Back to wards</Link><Link className="btn-ledger-primary" to={`/wards/${ward.id}/edit`}>Edit ward</Link></div>} /><section className="reference-surface facility-detail-cards"><article><span>CLINIC</span><strong>{ward.clinic?.name || `Clinic #${ward.clinic_id}`}</strong></article><article><span>WARD TYPE</span><strong>{ward.ward_type}</strong></article><article><span>STATUS</span><strong><span className={`status-pill status-${ward.status}`}>{ward.status}</span></strong></article><article><span>CONFIGURED ROOMS</span><strong>{ward.rooms_count ?? 0}</strong></article><article className="is-wide"><span>DESCRIPTION</span><strong>{ward.description || 'No ward note recorded.'}</strong></article></section></section>; }
