// Final clinical workspace: branch administration stays scoped to the parent clinic and uses live Laravel branch APIs.
import { useEffect, useState } from 'react';
import { useOutletContext } from 'react-router-dom';
import apiClient from '../../services/apiClient.js';
import PageHeader from '../../components/PageHeader.jsx';
import { EmptyPanel, ErrorPanel, LoadingPanel } from '../../components/StatePanel.jsx';
import { notify } from '../../services/notify.js';
import { FieldError, FormErrorSummary, clearFieldError } from '../../components/FormFeedback.jsx';
import Pagination from '../../components/Pagination.jsx';

const blank = (clinicId = '') => ({ clinic_id: clinicId, branch_code: '', branch_name: '', address: '', phone: '', email: '', contact_person: '', status: 'active' });
const suggestedBranchCode = (name, records) => { const stem = String(name || '').trim().toUpperCase().replace(/[^A-Z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 12) || 'BRANCH'; const prefix = `BR-${stem}`; const used = new Set(records.map((item) => item.branch_code)); let index = 1; while (used.has(`${prefix}-${String(index).padStart(2, '0')}`)) index += 1; return `${prefix}-${String(index).padStart(2, '0')}`; };

export default function BranchesIndex() {
  const { user } = useOutletContext();
  const [items, setItems] = useState([]); const [pagination, setPagination] = useState({ current_page: 1, last_page: 1, total: 0, per_page: 10 }); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [filters, setFilters] = useState({ search: '', status: '' }); const [editing, setEditing] = useState(null); const [form, setForm] = useState(() => blank(user?.clinic_id || '')); const [fieldErrors, setFieldErrors] = useState({}); const [saving, setSaving] = useState(false); const [openForm, setOpenForm] = useState(false);
  const load = (requestedPage = page) => { setLoading(true); const params = new URLSearchParams({ page: String(requestedPage), per_page: '10' }); if (filters.search) params.set('search', filters.search); if (filters.status) params.set('status', filters.status); apiClient.get(`/clinic-branches?${params}`).then((response) => { const payload = response.data.data || {}; setItems(payload.items || []); setPagination(payload.pagination || {}); setError(''); }).catch((requestError) => setError(requestError?.response?.data?.message || 'Unable to load clinic branches.')).finally(() => setLoading(false)); };
  useEffect(() => { setPage(1); load(1); }, [filters.status]);
  const update = (field, value) => { setForm((current) => ({ ...current, [field]: value, ...(field === 'branch_name' && !editing && !current.branch_code ? { branch_code: suggestedBranchCode(value, items) } : {}) })); setFieldErrors((current) => clearFieldError(current, field)); };
  const reset = () => { setEditing(null); setForm(blank(user?.clinic_id || '')); setFieldErrors({}); setOpenForm(false); };
  const edit = (branch) => { setEditing(branch); setForm({ ...blank(branch.clinic_id), ...branch }); setFieldErrors({}); setOpenForm(true); };
  const submit = async (event) => { event.preventDefault(); setSaving(true); setFieldErrors({}); try { await (editing ? apiClient.put(`/clinic-branches/${editing.id}`, form) : apiClient.post('/clinic-branches', form)); reset(); load(); } catch (requestError) { if (requestError?.response?.status === 422) setFieldErrors(requestError.response.data.errors || { form: [requestError.message] }); else notify.error(requestError, 'Unable to save this branch right now. Please try again.'); } finally { setSaving(false); } };
  const remove = async (branch) => { const result = await notify.confirm({ title: `Delete ${branch.branch_name}?`, text: 'Branches with assigned patient records cannot be deleted. You can deactivate the branch instead.', confirmButtonText: 'Delete branch' }); if (!result.isConfirmed) return; try { const response = await apiClient.delete(`/clinic-branches/${branch.id}`); notify.success('Branch deleted', response.data.message); load(); } catch (requestError) { notify.error(requestError, 'This branch cannot be deleted while it has dependent records.'); } };
  return <section className="routed-page final-branch-page"><PageHeader eyebrow="ADMINISTRATION · CLINIC BRANCHES" title="Clinic branches" description="Manage physical care locations under the selected parent clinic. Existing patient records remain protected when a branch is deactivated or has dependencies." crumbs={[{ label: 'Clinics', to: '/clinics' }, { label: 'Branches' }]} action={<button className="btn-ledger-primary" type="button" onClick={() => { reset(); setOpenForm(true); }}>Add branch</button>} />
    {openForm && <section className="reference-surface branch-editor"><div className="document-section-heading"><div><span>{editing ? 'UPDATE BRANCH' : 'NEW BRANCH'}</span><h2>{editing ? editing.branch_name : 'Register a physical branch'}</h2></div><button className="btn-ledger-secondary" type="button" onClick={reset}>Close</button></div><form onSubmit={submit} className="branch-form-grid" noValidate><FormErrorSummary errors={fieldErrors} labels={{ branch_code: 'Branch code', branch_name: 'Branch name', contact_person: 'Contact person' }} /><Field label="Branch code" required value={form.branch_code} error={fieldErrors.branch_code} onChange={(value) => update('branch_code', value)} placeholder="e.g. MIR-01" /><Field label="Branch name" required value={form.branch_name} error={fieldErrors.branch_name} onChange={(value) => update('branch_name', value)} placeholder="e.g. Mirpur Branch" /><Field label="Phone" error={fieldErrors.phone} value={form.phone} onChange={(value) => update('phone', value)} /><Field label="Email" error={fieldErrors.email} type="email" value={form.email} onChange={(value) => update('email', value)} /><Field label="Contact person" error={fieldErrors.contact_person} value={form.contact_person} onChange={(value) => update('contact_person', value)} /><label className={`clinical-field ${fieldErrors.status?.length ? 'has-error' : ''}`}><span>Status</span><select className={`form-select ${fieldErrors.status?.length ? 'is-invalid' : ''}`} value={form.status} aria-invalid={fieldErrors.status?.length || undefined} onChange={(event) => update('status', event.target.value)}><option value="active">Active</option><option value="inactive">Inactive</option></select><FieldError messages={fieldErrors.status} id="branch-status-error" /></label><Field label="Address" error={fieldErrors.address} wide area value={form.address} onChange={(value) => update('address', value)} /><div className="branch-editor-actions"><button className="btn-ledger-secondary" type="button" onClick={reset}>Cancel</button><button className="btn-ledger-primary" disabled={saving}>{saving ? 'Saving…' : editing ? 'Update branch' : 'Save branch'}</button></div></form></section>}
    <section className="reference-surface branch-toolbar"><input className="form-control" value={filters.search} onChange={(event) => setFilters((current) => ({ ...current, search: event.target.value }))} onKeyDown={(event) => event.key === 'Enter' && load()} placeholder="Search branch name, code, or address" /><select className="form-select" value={filters.status} onChange={(event) => setFilters((current) => ({ ...current, status: event.target.value }))}><option value="">All branch statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select><button type="button" className="btn-ledger-secondary" onClick={load}>Apply filters</button></section>
    {loading ? <LoadingPanel label="Loading clinic branches…" /> : error ? <ErrorPanel message={error} retry={load} /> : !items.length ? <EmptyPanel title="No clinic branches found" body="Create the main or first physical care location for this clinic." action={<button className="btn-ledger-primary" type="button" onClick={() => setOpenForm(true)}>Add branch</button>} /> : <section className="reference-surface phase4-table-surface branch-table"><div className="phase4-surface-title"><span>PHYSICAL LOCATIONS</span><strong>{pagination.total ?? items.length} branches</strong></div><div className="table-responsive"><table className="table clinical-table"><thead><tr><th>Code</th><th>Branch</th><th>Contact</th><th>Patients</th><th>Status</th><th /></tr></thead><tbody>{items.map((branch) => <tr key={branch.id}><td><code>{branch.branch_code}</code></td><td><strong>{branch.branch_name}</strong><small>{branch.address || 'Address not recorded'}</small></td><td>{branch.phone || '—'}<small>{branch.email || branch.contact_person || '—'}</small></td><td>{branch.patients_count || 0}</td><td><span className={`billing-status billing-${branch.status === 'active' ? 'paid' : 'cancelled'}`}>{branch.status}</span></td><td className="row-actions"><button type="button" onClick={() => edit(branch)}>Edit</button><button type="button" onClick={() => remove(branch)}>Delete</button></td></tr>)}</tbody></table></div><Pagination meta={pagination} page={page} onChange={(nextPage) => { setPage(nextPage); load(nextPage); }} /></section>}</section>;
}

function Field({ label, value, onChange, error, type = 'text', required = false, placeholder, area = false, wide = false }) { const invalid = error?.length; return <label className={`clinical-field ${wide || area ? 'is-wide' : ''} ${invalid ? 'has-error' : ''}`}><span>{label}{required && <b>*</b>}</span>{area ? <textarea className={`form-control ${invalid ? 'is-invalid' : ''}`} rows="3" value={value || ''} aria-invalid={invalid || undefined} onChange={(event) => onChange(event.target.value)} /> : <input className={`form-control ${invalid ? 'is-invalid' : ''}`} type={type} required={required} value={value || ''} aria-invalid={invalid || undefined} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} />}<FieldError messages={error} /></label>; }
