// Reference clinical workspace: Phase 7 presents real operational analytics as restrained ledger surfaces, tables, and data-bound bars rather than fabricated dashboard art.
import { useEffect, useMemo, useState } from 'react';
import { Link, Navigate, useParams } from 'react-router-dom';
import apiClient from '../../services/apiClient.js';
import PageHeader from '../../components/PageHeader.jsx';
import { ErrorPanel, LoadingPanel } from '../../components/StatePanel.jsx';
import Pagination from '../../components/Pagination.jsx';

const configs = {
  patients: { label: 'Patient report', icon: '♙', description: 'Patient records, status, and clinic activity.', table: [['Patient', (x) => x.name], ['Patient number', (x) => x.patient_number], ['Gender', (x) => x.gender], ['Status', (x) => x.status]] },
  doctors: { label: 'Doctor report', icon: '✚', description: 'Active practitioners and departmental distribution.', department: true, table: [['Doctor', (x) => x.name], ['Registration', (x) => x.registration_number], ['Department', (x) => x.department?.name], ['Status', (x) => x.status]] },
  appointments: { label: 'Appointment report', icon: '◷', description: 'Scheduled clinic demand by status, date, department, and doctor.', department: true, doctor: true, date: true, table: [['Appointment', (x) => x.appointment_number], ['Patient', (x) => x.patient?.name], ['Doctor', (x) => x.doctor?.name], ['Date', (x) => `${x.appointment_date} · ${x.appointment_time}`], ['Status', (x) => x.status]] },
  opd: { label: 'OPD report', icon: '✚', description: 'Outpatient visit activity across clinicians and service units.', department: true, doctor: true, date: true, table: [['OPD visit', (x) => x.opd_number], ['Patient', (x) => x.patient?.name], ['Doctor', (x) => x.doctor?.name], ['Visited', (x) => textDate(x.visited_at)], ['Status', (x) => x.visit_status]] },
  ipd: { label: 'IPD report', icon: '▤', description: 'Inpatient admission activity, live census, and status.', doctor: true, date: true, table: [['Admission', (x) => x.admission_number], ['Patient', (x) => x.patient?.name], ['Doctor', (x) => x.doctor?.name], ['Location', (x) => [x.ward?.name, x.room?.room_number, x.bed?.bed_number].filter(Boolean).join(' · ')], ['Status', (x) => x.status]] },
  emergency: { label: 'Emergency report', icon: '!', description: 'Emergency intake by date, presentation type, and current status.', date: true, table: [['Emergency', (x) => x.emergency_number], ['Patient', (x) => x.patient?.name], ['Type', (x) => x.emergency_type], ['Registered', (x) => textDate(x.registered_at)], ['Status', (x) => x.status]] },
  revenue: { label: 'Revenue report', icon: '¤', description: 'Collected payments, invoice value, and open balance across a date range.', date: true, financial: true },
  payments: { label: 'Payment report', icon: '¤', description: 'Collections by date and payment method.', date: true, payment: true, table: [['Payment', (x) => x.payment_number], ['Patient', (x) => x.patient?.name], ['Method', (x) => x.payment_method?.replaceAll('_', ' ')], ['Paid at', (x) => textDate(x.paid_at)], ['Amount', (x) => money(x.amount)]] },
  outstanding: { label: 'Outstanding due report', icon: '◌', description: 'Unpaid and partially paid invoices with current balance.', date: true, financial: true, table: [['Invoice', (x) => x.invoice_number], ['Patient', (x) => x.patient?.name], ['Source', (x) => x.source_type?.toUpperCase()], ['Invoice total', (x) => money(x.total_amount)], ['Due', (x) => money(x.due_amount)], ['Status', (x) => x.status]] },
  beds: { label: 'Bed occupancy report', icon: '▦', description: 'Available and occupied bed capacity by current operational state.', table: [['Bed', (x) => x.bed_number], ['Room', (x) => x.room?.room_number], ['Ward', (x) => x.room?.ward?.name], ['Type', (x) => x.bed_type], ['Status', (x) => x.status]] },
};
const unpack = (response) => response.data.data?.items || response.data.data || [];

export function ReportsDashboard() { return <section className="routed-page phase7-page"><PageHeader eyebrow="PHASE 7 · REPORTS" title="Reports dashboard" description="Open secured, database-backed reports for care activity, financial collections, outstanding balances, and bed capacity." crumbs={[{ label: 'Reports' }]} /><section className="report-card-grid">{Object.entries(configs).map(([key, config]) => <Link className="reference-surface report-nav-card" key={key} to={`/reports/${key}`}><i>{config.icon}</i><div><span>LIVE REPORT</span><h2>{config.label}</h2><p>{config.description}</p></div><em>Open →</em></Link>)}</section></section>; }

export function ReportPage() {
  const { reportType } = useParams(); const config = configs[reportType]; const [data, setData] = useState(null); const [catalogue, setCatalogue] = useState({ clinics: [], departments: [], doctors: [] }); const [filters, setFilters] = useState({ clinic_id: '', date_from: '', date_to: '', department_id: '', doctor_id: '', status: '' }); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { if (!config) return; Promise.all([apiClient.get('/clinics?per_page=100'), apiClient.get('/departments?per_page=100'), apiClient.get('/doctors?per_page=100')]).then(([clinics, departments, doctors]) => setCatalogue({ clinics: unpack(clinics), departments: unpack(departments), doctors: unpack(doctors) })).catch(() => {}); }, [reportType]);
  const load = (requestedPage = page) => { if (!config) return; setLoading(true); const params = new URLSearchParams({ page: String(requestedPage), per_page: '10' }); Object.entries(filters).forEach(([key, value]) => value && params.set(key, value)); apiClient.get(`/reports/${reportType}?${params}`).then((response) => { setData(response.data.data); setError(''); }).catch((err) => setError(err?.message || 'Unable to load this report.')).finally(() => setLoading(false)); };
  useEffect(() => { setPage(1); load(1); }, [reportType]); if (!config) return <Navigate to="/reports" replace />; const update = (key, value) => setFilters((current) => ({ ...current, [key]: value })); const apply = () => { setPage(1); load(1); }; const allowedDoctors = catalogue.doctors.filter((doctor) => !filters.clinic_id || String(doctor.clinic_id) === String(filters.clinic_id)); const allowedDepartments = catalogue.departments.filter((department) => !filters.clinic_id || String(department.clinic_id) === String(filters.clinic_id));
  return <section className="routed-page phase7-page"><PageHeader eyebrow="PHASE 7 · REPORTS" title={config.label} description={config.description} crumbs={[{ label: 'Reports', to: '/reports' }, { label: config.label }]} /><section className="reference-surface report-filter-surface"><div className="phase4-surface-title"><span>FILTERS</span><strong>Live API query</strong></div><div className="report-filter-grid"><select className="form-select" value={filters.clinic_id} onChange={(event) => update('clinic_id', event.target.value)}><option value="">All authorized clinics</option>{catalogue.clinics.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select>{config.date && <><input className="form-control" type="date" value={filters.date_from} onChange={(event) => update('date_from', event.target.value)} aria-label="Date from" /><input className="form-control" type="date" value={filters.date_to} onChange={(event) => update('date_to', event.target.value)} aria-label="Date to" /></>}{config.department && <select className="form-select" value={filters.department_id} onChange={(event) => update('department_id', event.target.value)}><option value="">All departments</option>{allowedDepartments.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select>}{config.doctor && <select className="form-select" value={filters.doctor_id} onChange={(event) => update('doctor_id', event.target.value)}><option value="">All doctors</option>{allowedDoctors.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select>}<input className="form-control" value={filters.status} onChange={(event) => update('status', event.target.value)} placeholder={config.payment ? 'Payment method' : 'Status'} /><button className="btn-report-primary" type="button" onClick={apply}>Apply filters</button></div></section>{error ? <ErrorPanel message={error} retry={load} /> : loading ? <LoadingPanel label="Loading real report figures…" /> : <ReportData config={config} data={data} page={page} onPage={(nextPage) => { setPage(nextPage); load(nextPage); }} />}</section>;
}
function ReportData({ config, data, page, onPage }) { const summary = data?.summary || {}; const items = data?.items || []; const series = data?.series || groupSeries(summary); const seriesMoney = config.label === 'Revenue report' || config.label === 'Payment report' || config.label === 'Outstanding due report'; return <><section className="report-summary-grid">{summaryCards(summary).map(([label, value]) => <article className="reference-surface" key={label}><span>{label}</span><strong>{formatValue(label, value)}</strong></article>)}</section>{series.length > 0 && <section className="reference-surface report-chart-surface"><div className="phase4-surface-title"><span>LIVE DISTRIBUTION</span><strong>Real database aggregate</strong></div><div className="report-bars">{series.map((item) => <div className="report-bar" key={item.label || item.date}><span>{item.label || item.date}</span><div><i style={{ width: `${barWidth(item.value, series)}%` }} /></div><b>{seriesMoney ? money(item.value) : Number(item.value || 0).toLocaleString()}</b></div>)}</div></section>}{config.table && <section className="reference-surface phase4-table-surface"><div className="phase4-surface-title"><span>REPORT RECORDS</span><strong>{data?.pagination?.total ?? items.length} records</strong></div><div className="table-responsive"><table className="table clinical-table"><thead><tr>{config.table.map(([label]) => <th key={label}>{label}</th>)}</tr></thead><tbody>{items.map((item) => <tr key={item.id}>{config.table.map(([label, render]) => <td key={label}>{render(item) || '—'}</td>)}</tr>)}</tbody></table></div>{!items.length && <div className="phase4-empty">No records match the active report filters.</div>}<Pagination meta={data?.pagination} page={page} onChange={onPage} /></section>}</>;
}
function summaryCards(summary) { return Object.entries(summary).filter(([, value]) => typeof value !== 'object'); }
function groupSeries(summary) { const grouped = ['by_status', 'by_type', 'by_method'].map((key) => summary[key]).find(Boolean) || {}; return Object.entries(grouped).map(([label, value]) => ({ label: label.replaceAll('_', ' '), value })); }
function barWidth(value, series) { const max = Math.max(...series.map((item) => Number(item.value || 0)), 1); return Math.max((Number(value || 0) / max) * 100, 2); }
function formatValue(label, value) { return /(collected|outstanding|amount|due|invoice)/i.test(label) ? money(value) : Number(value).toLocaleString(); }
function money(value) { return `৳${Number(value || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }
function textDate(value) { return value ? new Date(value).toLocaleString() : ''; }
