// Five Theme Demos: isolated visual comparison screens only. They use no API data, do not create sessions, and never modify the production theme.
import { useState } from 'react';
import { Activity, Bell, Building2, CalendarDays, ClipboardList, FileText, LayoutDashboard, LockKeyhole, Search, Sparkles, Stethoscope, Users } from 'lucide-react';

const themes = [
  { id: 1, key: 'clinical-sage', title: 'Clinical White + Soft Sage + Navy', label: 'PREMIUM PRIVATE HOSPITAL', text: 'Calm white surfaces, soft sage active states, and navy structure for a premium care setting.', icon: Building2, colors: ['#F7F9F8', '#2F6B5F', '#172B2A'] },
  { id: 2, key: 'enterprise-cyan', title: 'White + Deep Blue + Cyan', label: 'ENTERPRISE HEALTHCARE', text: 'Deep blue ownership, cyan signals, and concise white work surfaces for a large hospital system.', icon: Activity, colors: ['#F6F8FB', '#175CD3', '#06A6C7'] },
  { id: 3, key: 'teal-slate', title: 'White + Teal + Slate', label: 'MODERN SAAS HEALTHCARE', text: 'A purposeful teal accent and slate hierarchy that feel modern without losing clinical clarity.', icon: Stethoscope, colors: ['#F8FAFA', '#087F8C', '#4B636E'] },
  { id: 4, key: 'purple-blue', title: 'White + Purple + Blue', label: 'DIGITAL HEALTHCARE', text: 'Light technical purple states and blue actions for a more digital, SaaS-led clinic experience.', icon: Sparkles, colors: ['#F8F9FC', '#6D5DFB', '#3975E8'] },
  { id: 5, key: 'dark-dashboard', title: 'Dark Dashboard', label: 'PREMIUM DARK ENTERPRISE', text: 'A restrained dark operations canvas with soft-gray content and a muted teal clinical signal.', icon: ClipboardList, colors: ['#111827', '#0F172A', '#2F9E8F'] },
];

function MiniLogin({ theme }) { return <section className={`blue-demo-login ${theme}`}><div className="blue-demo-login-top"><span><LockKeyhole /> Secure sign in</span><i>Staff</i></div><h3>Access workspace</h3><p>Use your approved account.</p><label>Work email<input disabled placeholder="name@hospital.com" /></label><label>Password<input disabled type="password" placeholder="Enter password" /></label><button type="button">Sign in <span>→</span></button><small>Continue with Google</small></section>; }

function MiniWorkspace({ theme }) { return <section className={`blue-demo-workspace ${theme}`}><aside><header><span><Building2 /></span><b>Hospital System</b></header><nav><span className="active"><LayoutDashboard />Dashboard</span><span><Users />Patients</span><span><CalendarDays />Appointments</span><span><ClipboardList />Clinical records</span><span><FileText />Reports</span></nav><footer><i />Authorized staff</footer></aside><main><header><div><small>OPERATIONS / OVERVIEW</small><b>Today’s workspace</b></div><div><Search /><Bell /><span>AM</span></div></header><section className="blue-demo-summary"><article><small>PATIENT RECORDS</small><b>Active queue</b><span>Review assigned records</span></article><article><small>CLINICAL WORKFLOW</small><b>Current visits</b><span>Work by clinic scope</span></article><article><small>FACILITY STATUS</small><b>Ready</b><span>Authorized access only</span></article></section><section className="blue-demo-table"><header><b>Recent activity</b><span>View all</span></header><div><i /><b>Record update</b><small>Clinical workflow</small><em>Authorized</em></div><div><i /><b>Scheduled visit</b><small>Operations queue</small><em>Current</em></div></section></main></section>; }

export default function BlueThemeDemos() { const [selected, setSelected] = useState(null); return <main className="blue-theme-gallery five-theme-gallery"><header className="blue-theme-gallery-header"><a href="/"><span><Building2 /></span>Hospital Management System</a><div><p>YOUR FIVE COLOR-SYSTEM DEMOS</p><h1>Compare your exact visual directions across login and daily clinic work.</h1><span>Each option pairs a card-based staff sign-in with a representative clinic workspace. These are visual prototypes only; they do not use live patient records or modify the production theme.</span></div></header><section className="blue-theme-grid">{themes.map((theme) => { const Icon = theme.icon; return <article className={`blue-theme-option theme-${theme.key} ${selected === theme.id ? 'is-selected' : ''}`} key={theme.id}><header><span>0{theme.id}</span><div><Icon /><b>{theme.title}</b></div><small>{theme.label}</small><p>{theme.text}</p><div className="theme-token-row" aria-label="Theme colors">{theme.colors.map((color) => <i key={color} style={{ backgroundColor: color }} title={color} />)}</div></header><div className="blue-theme-frames"><MiniLogin theme={theme.key} /><MiniWorkspace theme={theme.key} /></div><footer><button type="button" onClick={() => setSelected(theme.id)}>{selected === theme.id ? 'Selected — tell us in chat' : `Choose theme ${theme.id}`}</button><span>{selected === theme.id ? 'Marked as your direction' : 'Login + workspace demo'}</span></footer></article>; })}</section><p className="blue-theme-selection-note">After reviewing, send <strong>1</strong>, <strong>2</strong>, <strong>3</strong>, <strong>4</strong>, or <strong>5</strong> in chat. I will apply only your selected system to the real login page and full clinic workspace.</p></main>; }
