// Phase 3: wrappers keep routing separate from the reusable appointment form and detail view.
import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import apiClient from '../../services/apiClient.js';
import PageHeader from '../../components/PageHeader.jsx';
import { ErrorPanel, LoadingPanel } from '../../components/StatePanel.jsx';
import AppointmentForm from './AppointmentForm.jsx';

export function AppointmentCreate() { const navigate = useNavigate(); return <section className="routed-page"><PageHeader eyebrow=" APPOINTMENTS" title="Book appointment" description="Select an available doctor and create a clinic-scoped appointment." crumbs={[{ label: 'Appointments', to: '/appointments' }, { label: 'Book appointment' }]} /><AppointmentForm onSaved={(record) => navigate(`/appointments/${record.id}`)} onCancel={() => navigate('/appointments')} /></section>; }
export function AppointmentEdit() { const { appointmentId } = useParams(); const navigate = useNavigate(); const [record, setRecord] = useState(null); const [error, setError] = useState(''); useEffect(() => { apiClient.get(`/appointments/${appointmentId}`).then((response) => setRecord(response.data.data)).catch((err) => setError(err?.message || 'Unable to load appointment.')); }, [appointmentId]); if (error) return <section className="routed-page"><ErrorPanel message={error} retry={() => window.location.reload()} /></section>; if (!record) return <section className="routed-page"><LoadingPanel label="Loading appointment…" /></section>; return <section className="routed-page"><PageHeader eyebrow=" APPOINTMENTS" title="Update appointment" description="Update only a valid clinic relationship and available time window." crumbs={[{ label: 'Appointments', to: '/appointments' }, { label: record.appointment_number, to: `/appointments/${record.id}` }, { label: 'Edit' }]} /><AppointmentForm appointment={record} onSaved={(saved) => navigate(`/appointments/${saved.id}`)} onCancel={() => navigate(`/appointments/${record.id}`)} /></section>; }
export function AppointmentShow() { const { appointmentId } = useParams(); const [record, setRecord] = useState(null); const [error, setError] = useState(''); useEffect(() => { apiClient.get(`/appointments/${appointmentId}`).then((response) => setRecord(response.data.data)).catch((err) => setError(err?.message || 'Unable to load appointment.')); }, [appointmentId]); if (error) return <section className="routed-page"><ErrorPanel message={error} retry={() => window.location.reload()} /></section>; if (!record) return <section className="routed-page"><LoadingPanel label="Loading appointment…" /></section>; return <section className="routed-page profile-page"><PageHeader eyebrow="APPOINTMENTS" title={record.appointment_number} description="Appointment details and OPD registration context." crumbs={[{ label: 'Appointments', to: '/appointments' }, { label: record.appointment_number }]} action={<div className="profile-actions"><Link className="btn-ledger-secondary" to={`/appointments/${record.id}/edit`}>Edit</Link><Link className="btn-ledger-primary" to={`/opd-visits/new?appointment_id=${record.id}`}>Register OPD visit</Link></div>} /><section className="schedule-detail-card"><span>BOOKING DETAILS</span><h2>{record.patient?.name} with {record.doctor?.name}</h2><div><article><b>DATE & TIME</b><strong>{record.appointment_date} · {record.appointment_time}</strong></article><article><b>DEPARTMENT</b><strong>{record.department?.name || '—'}</strong></article><article><b>STATUS</b><strong>{record.status}</strong></article></div><p><b>Reason:</b> {record.reason || 'Not recorded'}<br /><b>Notes:</b> {record.notes || 'None'}</p></section></section>; }
