// Phase 3: authorized appointment registry with backend search, filters, pagination, and direct routes.
import { useEffect, useState } from 'react';
import { Link, useOutletContext } from 'react-router-dom';
import apiClient from '../../services/apiClient.js';
import PageHeader from '../../components/PageHeader.jsx';
import { EmptyPanel, ErrorPanel, LoadingPanel } from '../../components/StatePanel.jsx';
import { StatusBadge } from '../patients/PatientsIndex.jsx';
import Pagination from '../../components/Pagination.jsx';
import { usePermissions } from '../../hooks/usePermissions.js';

export default function AppointmentsIndex() {
  const { user } = useOutletContext(); const { can } = usePermissions(user); const [records, setRecords] = useState([]); const [pagination, setPagination] = useState({ current_page: 1, last_page: 1, total: 0 }); const [filters, setFilters] = useState({ search: '', date: '', status: '', page: 1 }); const [searchDraft, setSearchDraft] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async (next = filters) => { setLoading(true); setError(''); try { const params = new URLSearchParams({ page: String(next.page), per_page: '10' }); ['search', 'date', 'status'].forEach((key) => next[key] && params.set(key, next[key])); const response = await apiClient.get(`/appointments?${params}`); setRecords(response.data.data.items || []); setPagination(response.data.data.pagination || {}); } catch (requestError) { setError(requestError?.message || 'Unable to load appointments.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []); useEffect(() => { const timer = setTimeout(() => { if (searchDraft !== filters.search) { const next = { ...filters, search: searchDraft, page: 1 }; setFilters(next); load(next); } }, 350); return () => clearTimeout(timer); }, [searchDraft]); const setFilter = (field, value) => { const next = { ...filters, [field]: value, page: 1 }; setFilters(next); load(next); }; const clear = () => { const next = { search: '', date: '', status: '', page: 1 }; setSearchDraft(''); setFilters(next); load(next); };
  return <section className="routed-page clinical-index-page"><PageHeader eyebrow=" APPOINTMENTS" title="Appointment register" description="Book and manage available doctor appointments with clinic-scoped safeguards." crumbs={[{ label: 'Appointments' }]} action={can('appointments.create') && <Link className="btn-ledger-primary" to="/appointments/new">Add appointment</Link>} /><section className="index-controls appointment-index-controls"><div className="search-control"><span>⌕</span><input className="form-control" value={searchDraft} onChange={(event) => setSearchDraft(event.target.value)} placeholder="Search appointment, patient, or doctor" /><button type="button" onClick={() => setSearchDraft('')} aria-label="Clear search">×</button></div><input className="form-control" type="date" value={filters.date} onChange={(event) => setFilter('date', event.target.value)} /><select className="form-select" value={filters.status} onChange={(event) => setFilter('status', event.target.value)}><option value="">All statuses</option>{['scheduled', 'confirmed', 'completed', 'cancelled', 'no_show'].map((status) => <option value={status} key={status}>{status.replace('_', ' ')}</option>)}</select><button type="button" className="filter-reset" onClick={clear}>Reset</button></section>{error ? <ErrorPanel message={error} retry={() => load()} /> : loading ? <LoadingPanel label="Loading appointment register…" /> : records.length === 0 ? <EmptyPanel title="No appointments found" body="Adjust the filters or book the first available appointment." action={can('appointments.create') && <Link className="btn-ledger-primary" to="/appointments/new">Add appointment</Link>} /> : <section className="registry-panel routed-registry"><div className="registry-head"><span>APPOINTMENT REGISTER</span><strong>{pagination.total} total</strong></div><div className="table-responsive"><table className="table ledger-table"><thead><tr><th>Number</th><th>Patient</th><th>Doctor</th><th>Date & time</th><th>Type</th><th>Status</th><th /></tr></thead><tbody>{records.map((record) => <tr key={record.id}><td><code>{record.appointment_number}</code></td><td>{record.patient?.name}<small>{record.patient?.patient_number}</small></td><td>{record.doctor?.name}<small>{record.department?.name}</small></td><td>{record.appointment_date}<small>{record.appointment_time}</small></td><td>{record.appointment_type.replace('_', ' ')}</td><td><StatusBadge value={record.status} /></td><td className="table-actions"><Link to={`/appointments/${record.id}`}>View</Link>{can('appointments.update') && <Link to={`/appointments/${record.id}/edit`}>Edit</Link>}</td></tr>)}</tbody></table></div><Pagination pagination={pagination} onPage={(page) => { const next = { ...filters, page }; setFilters(next); load(next); }} /></section>}</section>;
}
