// Phase 3: shared JSX-only form primitives for appointment, OPD, consultation, and prescription workflows.
// Clinical Ledger field primitives: retain form contracts while visibly mapping Laravel field errors to their controls.
import { useId } from 'react';
import { FieldError } from '../../components/FormFeedback.jsx';

export function FormSection({ title, caption, children }) { return <section className="clinical-form-section"><header><strong>{title}</strong><p>{caption}</p></header><div className="clinical-fields-grid">{children}</div></section>; }
export function TextField({ label, value, onChange, error, placeholder, type = 'text', required = false, area = false, min, max }) { const errorId = useId(); const invalid = Array.isArray(error) && error.length; const props = { className: `${area ? 'form-control' : 'form-control'} ${invalid ? 'is-invalid' : ''}`, 'aria-invalid': invalid || undefined, 'aria-describedby': invalid ? errorId : undefined }; return <label className={`clinical-field ${area ? 'is-wide' : ''} ${invalid ? 'has-error' : ''}`}><span>{label}{required && <b>*</b>}</span>{area ? <textarea {...props} rows="4" value={value || ''} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} /> : <input {...props} type={type} min={min} max={max} value={value || ''} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} />}{invalid ? <FieldError messages={error} id={errorId} /> : null}</label>; }
export function SelectField({ label, value, options, onChange, error, required = false, disabled = false }) { const errorId = useId(); const invalid = Array.isArray(error) && error.length; return <label className={`clinical-field ${invalid ? 'has-error' : ''}`}><span>{label}{required && <b>*</b>}</span><select className={`form-select ${invalid ? 'is-invalid' : ''}`} value={value || ''} disabled={disabled} aria-invalid={invalid || undefined} aria-describedby={invalid ? errorId : undefined} onChange={(event) => onChange(event.target.value)}><option value="">Select {label}</option>{options.map(([id, name]) => <option value={id} key={id}>{name}</option>)}</select>{invalid ? <FieldError messages={error} id={errorId} /> : null}</label>; }
export function DateTimeText({ value }) { return value ? new Date(value).toLocaleString() : '—'; }
