// Professional prescription workspace: uses live OPD and medicine-master data only, with an A4-friendly clinical document preview.
import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import apiClient from '../../services/apiClient.js';
import PageHeader from '../../components/PageHeader.jsx';
import { EmptyPanel, ErrorPanel, LoadingPanel } from '../../components/StatePanel.jsx';
import MedicineSelect from '../../components/MedicineSelect.jsx';
import { notify } from '../../services/notify.js';
import { FieldError, FormErrorSummary, clearFieldError } from '../../components/FormFeedback.jsx';

const blankItem = () => ({ medicine: null, medicine_id: '', medicine_name: '', dosage: '', frequency: '', duration: '', instructions: '' });

export default function PrescriptionWorkspace({ mode = 'create' }) {
  const { visitId } = useParams(); const navigate = useNavigate(); const [visit, setVisit] = useState(null); const [saved, setSaved] = useState(null); const [loaded, setLoaded] = useState(false); const [form, setForm] = useState({ prescribed_at: new Date().toISOString().slice(0, 16), notes: '', items: [blankItem()] }); const [errors, setErrors] = useState({}); const [saving, setSaving] = useState(false);
  const load = async () => { try { const [visitResponse, prescriptionResponse] = await Promise.all([apiClient.get(`/opd-visits/${visitId}`), apiClient.get(`/opd-visits/${visitId}/prescription`)]); setVisit(visitResponse.data.data); const prescription = prescriptionResponse.data.data; if (prescription) { setSaved(prescription); setForm({ prescribed_at: prescription.prescribed_at?.slice(0, 16) || '', notes: prescription.notes || '', items: (prescription.items || []).map((item) => ({ ...blankItem(), ...item })) }); } } catch (error) { notify.error(error, 'Unable to load the prescription workspace.'); } finally { setLoaded(true); } };
  useEffect(() => { load(); }, [visitId]);
  const updateForm = (field, value) => { setForm((current) => ({ ...current, [field]: value })); setErrors((current) => clearFieldError(current, field)); };
  const updateItem = (index, patch) => { setForm((current) => ({ ...current, items: current.items.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item) })); setErrors((current) => Object.keys(patch).reduce((next, key) => clearFieldError(next, `items.${index}.${key}`), current)); };
  useEffect(() => { if (mode === 'create' && saved?.id) navigate(`/opd-visits/${visitId}/prescription`, { replace: true }); }, [mode, saved, visitId, navigate]);
  const save = async (event) => { event.preventDefault(); setSaving(true); setErrors({}); try { const payload = { prescribed_at: `${form.prescribed_at.replace('T', ' ')}:00`, notes: form.notes, items: form.items.map(({ medicine, ...item }) => item) }; await apiClient.put(`/opd-visits/${visitId}/prescription`, payload); notify.success(mode === 'edit' ? 'Prescription updated.' : 'Prescription created.'); navigate(`/opd-visits/${visitId}/prescription`); } catch (error) { if (error?.response?.status === 422) setErrors(error.response.data.errors || { form: [error.message] }); else { setErrors({ form: [error?.message || 'Unable to save this prescription.'] }); notify.error(error, 'Unable to save this prescription right now. Please try again.'); } } finally { setSaving(false); } };
  if (!visit) return <section className="routed-page"><LoadingPanel label="Loading prescription workspace…" /></section>;
  if (mode === 'edit' && loaded && !saved) return <section className="routed-page"><EmptyPanel title="No prescription has been created" body="Create a prescription for this OPD visit before attempting to edit it." action={<Link className="btn-ledger-primary" to={`/opd-visits/${visitId}/prescription/create`}>Create prescription</Link>} /></section>;
  const clinicName = visit.clinic?.name || visit.patient?.clinic?.name || 'Clinic name not recorded'; const branch = visit.patient?.clinic_branch;
  return <section className="routed-page prescription-workspace"><PageHeader eyebrow="CLINICAL DOCUMENT · PRESCRIPTION" title={`${mode === 'edit' ? 'Edit' : 'Create'} prescription · ${visit.opd_number}`} description="Record protected prescription directions in the dedicated clinical editor. The patient-facing document is available only from the prescription view." crumbs={[{ label: 'OPD visits', to: '/opd-visits' }, { label: visit.opd_number, to: `/opd-visits/${visitId}` }, { label: 'Prescription', to: `/opd-visits/${visitId}/prescription` }, { label: mode === 'edit' ? 'Edit' : 'Create' }]} action={<Link className="btn-ledger-secondary" to={`/opd-visits/${visitId}/prescription`}>View prescription</Link>} />
    <form className="clinical-form-shell no-print" onSubmit={save} noValidate><FormErrorSummary errors={errors} labels={{ prescribed_at: 'Prescribed date and time', notes: 'Clinical notes' }} /><section className="clinical-form-section"><header><strong>Prescription details</strong><p>Clinical directions are retained in the protected OPD record.</p></header><div className="clinical-fields-grid"><Field label="Prescribed at" required type="datetime-local" value={form.prescribed_at} error={errors.prescribed_at} onChange={(value) => updateForm('prescribed_at', value)} /><Field label="Clinical notes" area value={form.notes} error={errors.notes} onChange={(value) => updateForm('notes', value)} placeholder="Add only clinically relevant prescription notes" /></div></section><section className="clinical-form-section"><header><strong>Medicine directions</strong><p>Medicine names are selected from the clinic medicine master. Dosage, frequency, duration, and instructions remain clinical entries.</p></header>{form.items.map((item, index) => <div className="rx-entry-row" key={index}><MedicineSelect clinicId={visit.clinic_id} value={item.medicine} onChange={(medicine) => updateItem(index, medicine ? { medicine, medicine_id: medicine.id, medicine_name: medicine.display_name } : { medicine: null, medicine_id: '', medicine_name: '' })} error={errors[`items.${index}.medicine_id`] || errors[`items.${index}.medicine_name`]} /><Field label="Dosage" value={item.dosage} error={errors[`items.${index}.dosage`]} onChange={(value) => updateItem(index, { dosage: value })} /><Field label="Frequency" value={item.frequency} error={errors[`items.${index}.frequency`]} onChange={(value) => updateItem(index, { frequency: value })} /><Field label="Duration" value={item.duration} error={errors[`items.${index}.duration`]} onChange={(value) => updateItem(index, { duration: value })} /><Field label="Instructions" area value={item.instructions} error={errors[`items.${index}.instructions`]} onChange={(value) => updateItem(index, { instructions: value })} />{form.items.length > 1 && <button className="rx-remove" type="button" onClick={() => setForm({ ...form, items: form.items.filter((_, itemIndex) => itemIndex !== index) })}>Remove</button>}</div>)}<button className="btn-ledger-secondary" type="button" onClick={() => setForm({ ...form, items: [...form.items, blankItem()] })}>+ Add medicine row</button></section><div className="clinical-form-footer"><p>{mode === 'edit' ? 'Save changes to update this prescription.' : 'Save to create the patient prescription.'}</p><div><button type="button" className="btn-ledger-secondary" onClick={() => navigate(`/opd-visits/${visitId}/prescription`)}>Cancel</button><button type="submit" className="btn-ledger-primary" disabled={saving}>{saving ? 'Saving prescription…' : mode === 'edit' ? 'Update prescription' : 'Create prescription'}</button></div></div></form>
  </section>;
}

export function PrescriptionViewPage() { const { visitId } = useParams(); const [visit, setVisit] = useState(null); const [prescription, setPrescription] = useState(null); const [error, setError] = useState(''); useEffect(() => { Promise.all([apiClient.get(`/opd-visits/${visitId}`), apiClient.get(`/opd-visits/${visitId}/prescription`)]).then(([visitResponse, prescriptionResponse]) => { setVisit(visitResponse.data.data); setPrescription(prescriptionResponse.data.data); }).catch((reason) => setError(reason?.response?.data?.message || 'Unable to load this prescription.')); }, [visitId]); if (error) return <section className="routed-page"><ErrorPanel message={error} retry={() => window.location.reload()} /></section>; if (!visit) return <section className="routed-page"><LoadingPanel label="Loading prescription…" /></section>; if (!prescription) return <section className="routed-page"><PageHeader eyebrow="CLINICAL DOCUMENT · PRESCRIPTION" title={`Prescription · ${visit.opd_number}`} description="No prescription is attached to this OPD visit yet." crumbs={[{ label: 'OPD visits', to: '/opd-visits' }, { label: visit.opd_number, to: `/opd-visits/${visitId}` }, { label: 'Prescription' }]} /><EmptyPanel title="No prescription created" body="Create the first prescription for this OPD visit using the clinic medicine master." action={<Link className="btn-ledger-primary" to={`/opd-visits/${visitId}/prescription/create`}>Create prescription</Link>} /></section>; const clinicName = visit.clinic?.name || visit.patient?.clinic?.name || 'Clinic name not recorded'; const branch = visit.patient?.clinic_branch; return <section className="routed-page prescription-workspace"><PageHeader eyebrow="CLINICAL DOCUMENT · PRESCRIPTION" title={`Prescription · ${prescription.prescription_number || visit.opd_number}`} description="Review the issued patient prescription. Use Edit only when clinical directions must be changed." crumbs={[{ label: 'OPD visits', to: '/opd-visits' }, { label: visit.opd_number, to: `/opd-visits/${visitId}` }, { label: 'Prescription' }]} action={<div className="profile-actions"><Link className="btn-ledger-secondary" to={`/opd-visits/${visitId}`}>Back to OPD visit</Link><Link className="btn-ledger-secondary" to={`/opd-visits/${visitId}/prescription/print`}>Print prescription</Link><Link className="btn-ledger-primary" to={`/opd-visits/${visitId}/prescription/edit`}>Edit prescription</Link></div>} /><PrescriptionDocument visit={visit} prescription={prescription} clinicName={clinicName} branch={branch} /></section>; }

export function PrescriptionDocument({ visit, prescription, clinicName, branch }) { return <article className="document-paper prescription-document page-break-avoid"><header className="document-paper-head"><div><span>CLINICAL PRESCRIPTION</span><h2>{clinicName}</h2><p>{branch ? `${branch.branch_name} · ${branch.address || 'Address not recorded'} · ${branch.phone || 'Contact not recorded'}` : 'Branch/contact information not recorded'}</p></div><div><span>RX NUMBER</span><strong>{prescription.prescription_number || 'Not issued yet'}</strong><small>{prescription.prescribed_at ? new Date(prescription.prescribed_at).toLocaleString() : 'Date not recorded'}</small></div></header><div className="document-paper-body"><div className="medical-summary-grid"><article><small>PATIENT</small><b>{visit.patient?.name || 'Not recorded'}</b><span>{visit.patient?.patient_number || 'ID not recorded'}</span></article><article><small>DOCTOR</small><b>{visit.doctor?.name || 'Not recorded'}</b><span>{visit.department?.name || 'Department not recorded'}</span></article><article><small>CLINICAL CONTEXT</small><b>{visit.opd_number}</b><span>{visit.symptoms || 'Symptoms not recorded'}</span></article></div><section className="rx-document-section"><div className="rx-mark">℞</div><div><p className="document-paper-label">MEDICINE DIRECTIONS</p><table className="table clinical-table"><thead><tr><th>Medicine</th><th>Dosage</th><th>Frequency</th><th>Duration</th><th>Instructions</th></tr></thead><tbody>{(prescription.items || []).map((item, index) => <tr key={item.id || index}><td><strong>{item.medicine_name || item.medicine?.display_name || 'Medicine not selected'}</strong></td><td>{item.dosage || '—'}</td><td>{item.frequency || '—'}</td><td>{item.duration || '—'}</td><td>{item.instructions || '—'}</td></tr>)}</tbody></table></div></section>{prescription.notes && <section className="document-clinical-note"><span>CLINICAL NOTES</span><p>{prescription.notes}</p></section>}<footer className="doctor-signature"><div><span>Prepared from protected clinic records</span><strong>{visit.doctor?.name || 'Doctor not recorded'}</strong><small>Authorized clinician</small></div><div className="signature-line" /></footer></div></article>; }
function Field({ label, value, onChange, error, area = false, required = false, type = 'text', placeholder }) { const invalid = error?.length; return <label className={`clinical-field ${area ? 'is-wide' : ''} ${invalid ? 'has-error' : ''}`}><span>{label}{required && <b>*</b>}</span>{area ? <textarea className={`form-control ${invalid ? 'is-invalid' : ''}`} rows="2" value={value || ''} aria-invalid={invalid || undefined} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} /> : <input className={`form-control ${invalid ? 'is-invalid' : ''}`} required={required} type={type} value={value || ''} aria-invalid={invalid || undefined} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} />}<FieldError messages={error} /></label>; }
