// Reusable async entity picker: returns the existing Laravel entity object while parents keep their current numeric ID payloads.
import { useEffect, useId, useRef, useState } from 'react';
import apiClient from '../services/apiClient.js';
import { FieldError } from './FormFeedback.jsx';

const unpack = (response) => response.data.data?.items || response.data.data || [];

export default function AsyncEntitySelect({ label, endpoint, baseParams = {}, value, onSelect, format, placeholder, error, required = false, disabled = false }) {
  const root = useRef(null); const listId = useId(); const [query, setQuery] = useState(value ? format(value) : ''); const [items, setItems] = useState([]); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(false); const [active, setActive] = useState(-1);
  useEffect(() => { if (!open || disabled) return undefined; const timer = setTimeout(async () => { setLoading(true); try { const params = new URLSearchParams({ per_page: '10', ...Object.fromEntries(Object.entries(baseParams).filter(([, item]) => item !== '' && item != null)) }); if (query.trim()) params.set('search', query.trim()); const response = await apiClient.get(`${endpoint}?${params}`); setItems(unpack(response)); setActive(-1); } catch { setItems([]); } finally { setLoading(false); } }, query.trim() ? 260 : 0); return () => clearTimeout(timer); }, [open, query, endpoint, JSON.stringify(baseParams), disabled]);
  useEffect(() => { const close = (event) => { if (root.current && !root.current.contains(event.target)) setOpen(false); }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close); }, []);
  useEffect(() => { if (value) setQuery(format(value)); }, [value?.id]);
  const choose = (item) => { onSelect(item); setQuery(format(item)); setOpen(false); setActive(-1); };
  const clear = () => { onSelect(null); setQuery(''); setOpen(false); setItems([]); setActive(-1); };
  const keyDown = (event) => { if (event.key === 'ArrowDown') { event.preventDefault(); setOpen(true); setActive((current) => Math.min(current + 1, Math.max(items.length - 1, 0))); } else if (event.key === 'ArrowUp') { event.preventDefault(); setActive((current) => Math.max(current - 1, 0)); } else if (event.key === 'Enter' && open && active >= 0 && items[active]) { event.preventDefault(); choose(items[active]); } else if (event.key === 'Escape') { setOpen(false); } };
  const invalid = error?.length;
  return <label ref={root} className={`clinical-field async-entity-select ${invalid ? 'has-error' : ''}`}><span>{label}{required && <b>*</b>}</span><div className="async-entity-control"><input className={`form-control ${invalid ? 'is-invalid' : ''}`} value={query} disabled={disabled} role="combobox" aria-expanded={open} aria-controls={listId} aria-autocomplete="list" aria-invalid={invalid || undefined} placeholder={placeholder || `Search ${label.toLowerCase()}`} autoComplete="off" onFocus={() => setOpen(true)} onChange={(event) => { setQuery(event.target.value); onSelect(null); setOpen(true); }} onKeyDown={keyDown} />{value && <button type="button" className="async-entity-clear" onClick={clear} aria-label={`Clear ${label}`}>×</button>}{loading && <span className="async-entity-loading">Searching…</span>}</div>{open && !disabled && <div className="async-entity-results" id={listId} role="listbox">{items.length ? items.map((item, index) => <button type="button" key={item.id} role="option" aria-selected={active === index} className={active === index ? 'is-active' : ''} onMouseDown={(event) => event.preventDefault()} onClick={() => choose(item)}>{format(item)}</button>) : <p>{query.trim() ? `No ${label.toLowerCase()} matches found.` : `Type to search ${label.toLowerCase()} records.`}</p>}</div>}<FieldError messages={error} /></label>;
}
