// Clinical medicine picker: searches the existing Laravel medicine master and returns the selected record unchanged to prescription and invoice forms.
import { useEffect, useId, useRef, useState } from 'react';
import apiClient from '../services/apiClient.js';
import { FieldError } from './FormFeedback.jsx';

export default function MedicineSelect({ clinicId, value, onChange, error, label = 'Medicine', required = true }) {
  const root = useRef(null); const [search, setSearch] = useState(value?.display_name || ''); const [items, setItems] = useState([]); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(false); const [active, setActive] = useState(-1); const listId = useId();
  useEffect(() => { if (!clinicId || !open) { setItems([]); return undefined; } const timer = setTimeout(async () => { setLoading(true); try { const query = search.trim() ? `&search=${encodeURIComponent(search.trim())}` : ''; const response = await apiClient.get(`/medicines?clinic_id=${clinicId}&status=active${query}&per_page=12`); setItems(response.data.data.items || []); setActive(-1); } catch { setItems([]); } finally { setLoading(false); } }, search.trim() ? 220 : 0); return () => clearTimeout(timer); }, [clinicId, search, open]);
  useEffect(() => { const close = (event) => { if (root.current && !root.current.contains(event.target)) setOpen(false); }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close); }, []);
  useEffect(() => { if (value?.id) setSearch(value.display_name); }, [value?.id]);
  const choose = (medicine) => { onChange(medicine); setSearch(medicine.display_name); setOpen(false); setActive(-1); };
  const clear = () => { onChange(null); setSearch(''); setItems([]); setOpen(false); setActive(-1); };
  const browse = () => { if (!clinicId) return; setOpen(true); };
  const keyDown = (event) => { if (event.key === 'Escape') { setOpen(false); return; } if (event.key === 'ArrowDown') { event.preventDefault(); setOpen(true); setActive((current) => Math.min(current + 1, Math.max(items.length - 1, 0))); } if (event.key === 'ArrowUp') { event.preventDefault(); setActive((current) => Math.max(current - 1, 0)); } if (event.key === 'Enter' && open && active >= 0 && items[active]) { event.preventDefault(); choose(items[active]); } };
  const invalid = error?.length;
  return <label ref={root} className={`clinical-field medicine-picker ${invalid ? 'has-error' : ''}`}><span>{label}{required && <b>*</b>}</span><div className="medicine-picker-control"><input className={`form-control ${invalid ? 'is-invalid' : ''}`} value={search} role="combobox" aria-expanded={open} aria-controls={listId} aria-autocomplete="list" aria-invalid={invalid || undefined} aria-describedby={invalid ? 'medicine-select-error' : undefined} onFocus={() => setOpen(true)} onKeyDown={keyDown} onChange={(event) => { setSearch(event.target.value); onChange(null); setOpen(true); }} placeholder={clinicId ? 'Search medicine name, code, or strength' : 'Select a clinic first'} disabled={!clinicId} autoComplete="off" />{value?.id && <button className="medicine-picker-clear" type="button" onMouseDown={(event) => event.preventDefault()} onClick={clear} aria-label="Clear selected medicine">×</button>}<button className="medicine-picker-browse" type="button" onMouseDown={(event) => event.preventDefault()} onClick={browse} disabled={!clinicId} aria-label="Browse available medicines">⌄ Browse</button>{loading && <em>Searching…</em>}</div>{open && clinicId && <div className="medicine-picker-results" id={listId} role="listbox">{items.length ? items.map((medicine, index) => <button type="button" role="option" aria-selected={value?.id === medicine.id} className={active === index ? 'is-active' : ''} key={medicine.id} onMouseDown={(event) => event.preventDefault()} onClick={() => choose(medicine)}><strong>{medicine.display_name}</strong><small>{medicine.medicine_code} · ৳{Number(medicine.default_unit_price || 0).toFixed(2)}</small></button>) : <p>{search.trim() ? 'No active medicine matches. Add it in Medicine master first.' : 'No active medicines are available for this clinic.'}</p>}</div>}{value?.id && <small className="medicine-picker-selected">Selected master medicine · {value.medicine_code} · ৳{Number(value.default_unit_price || 0).toFixed(2)}</small>}<FieldError messages={error} id="medicine-select-error" /></label>;
}
