// Hospital patient profile: protected demographic data plus structured live appointment and OPD histories.
// Clinical White + Soft Sage + Navy: one calm patient profile work surface, preserving real patient data, actions, routes, and history workflows.
import { useEffect, useState } from 'react';
import { Link, useLocation, useNavigate, useOutletContext, useParams } from 'react-router-dom';
import apiClient from '../../services/apiClient.js';
import ConfirmDialog from '../../components/ConfirmDialog.jsx';
import PageHeader from '../../components/PageHeader.jsx';
import { ErrorPanel, LoadingPanel } from '../../components/StatePanel.jsx';
import { StatusBadge } from './PatientsIndex.jsx';
import { usePermissions } from '../../hooks/usePermissions.js';

export default function PatientShow() {
  const { patientId } = useParams(); const location = useLocation(); const navigate = useNavigate(); const { user } = useOutletContext(); const { can } = usePermissions(user);
  const [patient, setPatient] = useState(null); const [appointments, setAppointments] = useState([]); const [visits, setVisits] = useState([]); const [error, setError] = useState(''); const [confirm, setConfirm] = useState(false); const [deleting, setDeleting] = useState(false); const [notice] = useState(location.state?.notice || '');
  const load = () => { setPatient(null); setError(''); Promise.all([apiClient.get(`/patients/${patientId}`), apiClient.get(`/appointments?patient_id=${patientId}&per_page=5`), apiClient.get(`/opd-visits?patient_id=${patientId}&per_page=5`)]).then(([profile, appointmentResponse, visitResponse]) => { setPatient(profile.data.data); setAppointments(appointmentResponse.data.data?.items || []); setVisits(visitResponse.data.data?.items || []); }).catch((requestError) => setError(requestError?.message || 'Unable to load this patient record.')); };
  useEffect(load, [patientId]);
  const remove = async () => { setDeleting(true); try { await apiClient.delete(`/patients/${patientId}`); navigate('/patients', { state: { notice: 'Patient record deleted.' } }); } catch (requestError) { setError(requestError?.message || 'Unable to delete this patient record.'); setConfirm(false); } finally { setDeleting(false); } };
  if (error) return <section className="routed-page"><ErrorPanel message={error} retry={load} /></section>; if (!patient) return <section className="routed-page"><LoadingPanel label="Loading patient profile…" /></section>;
  return <section className="routed-page profile-page"><PageHeader eyebrow="PHASE 2–6 · PATIENT PROFILE" title={patient.name} description={`Patient ID ${patient.patient_number}`} crumbs={[{ label: 'Patients', to: '/patients' }, { label: patient.name }]} action={<div className="profile-actions"><Link className="btn-ledger-secondary" to="/patients">Back to patients</Link>{can('appointments.create') && <Link className="btn-ledger-secondary" to="/appointments/new">Book appointment</Link>}{can('invoices.view') && <Link className="btn-ledger-secondary" to={`/patients/${patient.id}/billing-history`}>Billing history</Link>}{can('patients.update') && <Link className="btn-ledger-primary" to={`/patients/${patient.id}/edit`}>Edit patient</Link>}</div>} />{notice && <div className="form-notice">{notice}</div>}<section className="patient-profile-surface"><header className="profile-hero patient-profile-hero"><div className="profile-avatar">{patient.name?.slice(0, 1)}</div><div><span>{patient.patient_number}</span><h2>{patient.name}</h2><p>{patient.gender} · {age(patient.date_of_birth)} · {patient.blood_group || 'Blood group not recorded'}</p></div><StatusBadge value={patient.status} /></header><div className="patient-profile-sections"><ProfileSection title="Personal information" data={[["Gender", patient.gender], ["Date of birth", patient.date_of_birth || 'Not recorded'], ["Blood group", patient.blood_group || 'Not recorded']]} /><ProfileSection title="Contact information" data={[["Phone", patient.phone], ["Email", patient.email], ["Address", patient.address]]} /><ProfileSection title="Emergency contact" data={[["Contact name", patient.emergency_contact_name], ["Contact phone", patient.emergency_contact_phone]]} /><ProfileSection title="Medical information" wide data={[["Allergies", patient.allergies], ["Medical history", patient.medical_history]]} /></div></section><section className="patient-history-grid"><AppointmentHistory records={appointments} /><HistoryCard label="OPD HISTORY" title="Outpatient visits" empty="No OPD visits recorded for this patient." records={visits} render={(record) => <Link to={`/opd-visits/${record.id}`}><b>{record.opd_number}</b><span>{new Date(record.visited_at).toLocaleString()}</span><small>{record.doctor?.name || 'Doctor not recorded'} · {record.visit_status}</small></Link>} /></section>{can('patients.delete') && <button className="profile-delete-link" type="button" onClick={() => setConfirm(true)}>Delete this patient record</button>}{confirm && <ConfirmDialog title="Delete patient record" description={`Delete ${patient.name}? The patient record will be soft-deleted.`} busy={deleting} onCancel={() => setConfirm(false)} onConfirm={remove} />}</section>;
}
function ProfileSection({ title, data, wide = false }) { return <section className={`patient-profile-section${wide ? ' is-wide' : ''}`}><h2>{title}</h2><dl>{data.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value || 'Not recorded'}</dd></div>)}</dl></section>; }
function HistoryCard({ label, title, empty, records, render }) { return <section className="phase3-history-card"><header><span>{label}</span><h2>{title}</h2></header>{records.length ? <div>{records.map((record) => <article key={record.id}>{render(record)}</article>)}</div> : <p>{empty}</p>}</section>; }
function AppointmentHistory({ records }) { return <section className="phase3-history-card appointment-history-card"><header><span>APPOINTMENT HISTORY</span><h2>Appointments</h2></header>{records.length ? <div className="table-responsive"><table className="table ledger-table"><thead><tr><th>Appointment</th><th>Date</th><th>Time</th><th>Doctor</th><th>Department</th><th>Status</th><th aria-label="Action" /></tr></thead><tbody>{records.map((record) => <tr key={record.id}><td><code>{record.appointment_number}</code></td><td>{record.appointment_date || '—'}</td><td>{record.appointment_time || '—'}</td><td>{record.doctor?.name || 'Doctor not recorded'}</td><td>{record.department?.name || record.doctor?.department?.name || 'Not recorded'}</td><td><StatusBadge value={record.status} /></td><td className="table-actions"><Link to={`/appointments/${record.id}`}>View</Link></td></tr>)}</tbody></table></div> : <p>No appointments recorded for this patient.</p>}</section>; }
function age(dateOfBirth) { if (!dateOfBirth) return 'Age not recorded'; return `${Math.floor((Date.now() - new Date(dateOfBirth).getTime()) / 31557600000)} years`; }
