// Clinical Ledger: availability windows are explicit, validated routes rather than embedded profile modal actions.
import { useEffect, useState } from 'react';
import apiClient from '../../services/apiClient.js';

const initialSchedule = { day_of_week: '', start_time: '', end_time: '', status: 'active' };
const dayOptions = [['0', 'Sunday'], ['1', 'Monday'], ['2', 'Tuesday'], ['3', 'Wednesday'], ['4', 'Thursday'], ['5', 'Friday'], ['6', 'Saturday']];

export default function DoctorScheduleForm({ doctorId, schedule, onSaved, onCancel }) {
  const [form, setForm] = useState(() => schedule ? normalize(schedule) : initialSchedule);
  const [errors, setErrors] = useState({}); const [saving, setSaving] = useState(false); const [dirty, setDirty] = useState(false);
  useEffect(() => { const warn = (event) => { if (dirty) { event.preventDefault(); event.returnValue = ''; } }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn); }, [dirty]);
  const update = (field, value) => { setForm((current) => ({ ...current, [field]: value })); setDirty(true); };
  const submit = async (event) => { event.preventDefault(); setSaving(true); setErrors({}); try { const payload = { ...form, day_of_week: Number(form.day_of_week) }; const response = schedule ? await apiClient.put(`/doctor-schedules/${schedule.id}`, payload) : await apiClient.post(`/doctors/${doctorId}/schedules`, payload); setDirty(false); onSaved(response.data.data, response.data.message); } catch (requestError) { setErrors(requestError?.errors || { form: [requestError?.message || 'Unable to save this availability window.'] }); } finally { setSaving(false); } };
  return <form className="clinical-form-shell schedule-page-form" onSubmit={submit} noValidate><div className="form-intro"><div><span>{schedule ? `${schedule.day_label} · ${schedule.start_time}–${schedule.end_time}` : 'NEW AVAILABILITY WINDOW'}</span><strong>{schedule ? 'Update schedule' : 'Add schedule'}</strong></div><p>Availability is a foundation for later appointment workflows; it does not create appointments in Phase 2.</p></div>{errors.form?.map((message) => <div className="form-notice is-error" key={message}>{message}</div>)}<section className="clinical-form-section"><header><strong>Weekly availability</strong><p>Each window must have a valid day and a start time earlier than the end time.</p></header><div className="clinical-fields-grid"><SelectField label="Day of week" required value={form.day_of_week} options={dayOptions} onChange={(value) => update('day_of_week', value)} error={errors.day_of_week} /><TimeField label="Start time" required value={form.start_time} onChange={(value) => update('start_time', value)} error={errors.start_time} /><TimeField label="End time" required value={form.end_time} onChange={(value) => update('end_time', value)} error={errors.end_time} /><SelectField label="Status" required value={form.status} options={[['active', 'Available'], ['inactive', 'Unavailable']]} onChange={(value) => update('status', value)} error={errors.status} /></div></section><div className="clinical-form-footer"><p>{dirty ? 'You have unsaved changes.' : 'The schedule window is ready to save.'}</p><div><button className="btn-ledger-secondary" type="button" onClick={onCancel} disabled={saving}>Cancel</button><button className="btn-ledger-primary" type="submit" disabled={saving}>{saving ? 'Saving schedule…' : schedule ? 'Update schedule' : 'Save schedule'}</button></div></div></form>;
}
function SelectField({ label, value, options, onChange, error, required = false }) { return <label className="clinical-field"><span>{label}{required && <b>*</b>}</span><select className="form-select" value={value || ''} onChange={(event) => onChange(event.target.value)}><option value="">Select {label}</option>{options.map(([id, name]) => <option value={id} key={id}>{name}</option>)}</select>{error?.map((message) => <small className="field-error" key={message}>{message}</small>)}</label>; }
function TimeField({ label, value, onChange, error, required }) { return <label className="clinical-field"><span>{label}{required && <b>*</b>}</span><input className="form-control" type="time" value={value || ''} onChange={(event) => onChange(event.target.value)} />{error?.map((message) => <small className="field-error" key={message}>{message}</small>)}</label>; }
function normalize(schedule) { return { day_of_week: String(schedule.day_of_week), start_time: schedule.start_time || '', end_time: schedule.end_time || '', status: schedule.status || 'active' }; }
