// Dedicated role screens reuse the existing Laravel /roles and /permissions contracts without changing authorization behavior.
import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import apiClient from '../../services/apiClient.js';
import PageHeader from '../../components/PageHeader.jsx';
import { EmptyPanel, ErrorPanel, LoadingPanel } from '../../components/StatePanel.jsx';
import { FormErrorSummary, clearFieldError } from '../../components/FormFeedback.jsx';
import { notify } from '../../services/notify.js';

const empty = { name: '', description: '', permission_ids: [] };
const unpack = (response) => response.data.data?.items || response.data.data || [];

export function RolesIndex() {
  const [roles, setRoles] = useState([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); apiClient.get('/roles').then((response) => { setRoles(unpack(response)); setError(''); }).catch((requestError) => setError(requestError?.message || 'Unable to load roles.')).finally(() => setLoading(false)); };
  useEffect(load, []);
  const remove = async (role) => { const confirmation = await notify.confirm({ title: `Delete ${role.name}?`, text: 'Roles assigned to users or protected system roles cannot be deleted.', confirmButtonText: 'Delete role' }); if (!confirmation.isConfirmed) return; try { await apiClient.delete(`/roles/${role.id}`); load(); } catch (requestError) { notify.error(requestError, 'Unable to delete this role.'); } };
  if (loading) return <section className="routed-page"><LoadingPanel label="Loading role directory…" /></section>;
  if (error) return <section className="routed-page"><ErrorPanel message={error} retry={load} /></section>;
  return <section className="routed-page clinical-index-page"><PageHeader eyebrow="ADMINISTRATION · ACCESS CONTROL" title="Role directory" description="Manage role definitions and their allowed operational permissions." crumbs={[{ label: 'Roles' }]} action={<Link className="btn-ledger-primary" to="/roles/new">Create role</Link>} />{roles.length ? <section className="registry-panel routed-registry"><div className="registry-head"><span>ROLE DIRECTORY</span><strong>{roles.length} roles</strong></div><div className="table-responsive"><table className="table ledger-table"><thead><tr><th>Role</th><th>Description</th><th>Permissions</th><th>Type</th><th aria-label="Actions" /></tr></thead><tbody>{roles.map((role) => <tr key={role.id}><td><strong>{role.name}</strong><small>{role.slug}</small></td><td>{role.description || 'No description recorded'}</td><td>{role.permissions?.length || 0}</td><td><span className={`status-badge ${role.is_system ? 'status-active' : 'status-pending'}`}>{role.is_system ? 'System' : 'Custom'}</span></td><td className="table-actions"><Link to={`/roles/${role.id}`}>View</Link><Link to={`/roles/${role.id}/edit`}>Edit</Link>{!role.is_system && <button type="button" onClick={() => remove(role)}>Delete</button>}</td></tr>)}</tbody></table></div></section> : <EmptyPanel title="No roles found" body="Create a role to define an authorized operational scope." action={<Link className="btn-ledger-primary" to="/roles/new">Create role</Link>} />}</section>;
}

export function RoleCreate() { const navigate = useNavigate(); return <RoleEditor title="Create role" description="Define a new role and select its authorized permissions." onCancel={() => navigate('/roles')} onSaved={(role) => navigate(`/roles/${role.id}`)} />; }
export function RoleEdit() { const { roleId } = useParams(); const navigate = useNavigate(); const [role, setRole] = useState(null); const [error, setError] = useState(''); useEffect(() => { apiClient.get(`/roles/${roleId}`).then((response) => setRole(response.data.data)).catch((requestError) => setError(requestError?.message || 'Unable to load role.')); }, [roleId]); if (error) return <section className="routed-page"><ErrorPanel message={error} retry={() => window.location.reload()} /></section>; if (!role) return <section className="routed-page"><LoadingPanel label="Loading role…" /></section>; return <RoleEditor role={role} title={`Edit ${role.name}`} description="Update the role description and permission scope while preserving existing Laravel rules for system roles." onCancel={() => navigate(`/roles/${roleId}`)} onSaved={(saved) => navigate(`/roles/${saved.id}`)} />; }

export function RoleShow() { const { roleId } = useParams(); const [role, setRole] = useState(null); const [error, setError] = useState(''); useEffect(() => { apiClient.get(`/roles/${roleId}`).then((response) => setRole(response.data.data)).catch((requestError) => setError(requestError?.response?.data?.message || 'Unable to load role.')); }, [roleId]); if (error) return <section className="routed-page"><ErrorPanel message={error} retry={() => window.location.reload()} /></section>; if (!role) return <section className="routed-page"><LoadingPanel label="Loading role details…" /></section>; return <section className="routed-page profile-page"><PageHeader eyebrow="ADMINISTRATION · ACCESS CONTROL" title={role.name} description="Review the role’s authorization scope before updating its allowed operational permissions." crumbs={[{ label: 'Roles', to: '/roles' }, { label: role.name }]} action={<div className="profile-actions"><Link className="btn-ledger-secondary" to="/roles">Back to roles</Link><Link className="btn-ledger-primary" to={`/roles/${role.id}/edit`}>Edit role</Link></div>} /><section className="reference-surface registry-detail-grid"><article><span>ROLE TYPE</span><strong>{role.is_system ? 'Protected system role' : 'Custom role'}</strong></article><article><span>ROLE SLUG</span><strong>{role.slug}</strong></article><article className="is-wide"><span>DESCRIPTION</span><strong>{role.description || 'No description recorded.'}</strong></article></section><section className="reference-surface phase4-table-surface"><div className="phase4-surface-title"><span>ASSIGNED PERMISSIONS</span><strong>{role.permissions?.length || 0} permissions</strong></div>{role.permissions?.length ? <div className="permission-picker role-detail-permissions">{role.permissions.map((permission) => <span className="permission-option" key={permission.id}>{permission.name}</span>)}</div> : <div className="phase4-empty">No permissions are assigned to this role.</div>}</section></section>; }

function RoleEditor({ role, title, description, onCancel, onSaved }) {
  const [form, setForm] = useState(() => role ? { name: role.name || '', description: role.description || '', permission_ids: role.permissions?.map((permission) => permission.id) || [] } : empty); const [permissions, setPermissions] = useState([]); const [errors, setErrors] = useState({}); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  useEffect(() => { apiClient.get('/permissions').then((response) => setPermissions(unpack(response))).catch((requestError) => setErrors({ form: [requestError?.message || 'Unable to load permissions.'] })).finally(() => setLoading(false)); }, []);
  const update = (field, value) => { setForm((current) => ({ ...current, [field]: value })); setErrors((current) => clearFieldError(current, field)); };
  const toggle = (id, checked) => update('permission_ids', checked ? [...form.permission_ids, id] : form.permission_ids.filter((permissionId) => permissionId !== id));
  const submit = async (event) => { event.preventDefault(); setSaving(true); setErrors({}); try { const response = role ? await apiClient.put(`/roles/${role.id}`, form) : await apiClient.post('/roles', form); notify.success(role ? 'Role updated' : 'Role created', response.data.message); onSaved(response.data.data); } catch (requestError) { setErrors(requestError?.response?.data?.errors || { form: [requestError?.message || 'Unable to save role.'] }); } finally { setSaving(false); } };
  if (loading) return <section className="routed-page"><LoadingPanel label="Loading permission matrix…" /></section>;
  return <section className="routed-page form-page"><PageHeader eyebrow="ADMINISTRATION · ACCESS CONTROL" title={title} description={description} crumbs={[{ label: 'Roles', to: '/roles' }, { label: title }]} action={<Link className="btn-ledger-secondary" to="/roles">← Back to roles</Link>} /><form className="clinical-form-shell" onSubmit={submit} noValidate><div className="form-intro"><div><span>{role?.slug || 'CUSTOM ROLE'}</span><strong>{role?.is_system ? 'System role permissions' : 'Role definition'}</strong></div><p>Authorization is enforced by the existing Laravel role and permission policies after this form is saved.</p></div><FormErrorSummary errors={errors} labels={{ name: 'Role name', description: 'Description', permission_ids: 'Permissions' }} /><section className="clinical-form-section"><header><strong>Role information</strong><p>Use a clear operational name and an optional description.</p></header><div className="clinical-fields-grid"><label className="clinical-field"><span>Role name<b>*</b></span><input className="form-control" required disabled={role?.is_system} value={form.name} onChange={(event) => update('name', event.target.value)} /></label><label className="clinical-field is-wide"><span>Description</span><textarea className="form-control" rows="3" value={form.description} onChange={(event) => update('description', event.target.value)} /></label></div></section><section className="clinical-form-section"><header><strong>Permission scope</strong><p>Select only the existing permissions required for this role.</p></header><fieldset className="permission-picker">{permissions.map((permission) => <label className="permission-option" key={permission.id}><input type="checkbox" checked={form.permission_ids.includes(permission.id)} onChange={(event) => toggle(permission.id, event.target.checked)} /><span>{permission.name}</span></label>)}</fieldset></section><div className="clinical-form-footer"><p>{role?.is_system ? 'System role names remain protected by the existing API.' : 'The API validates and stores this permission assignment.'}</p><div><button className="btn-ledger-secondary" type="button" onClick={onCancel}>Cancel</button><button className="btn-ledger-primary" disabled={saving}>{saving ? 'Saving…' : role ? 'Update role' : 'Create role'}</button></div></div></form></section>;
}
